vich_uploader:
    db_driver: orm

    mappings:
        header_illustration:
            uri_prefix: /uploads/headers
            upload_destination: '%kernel.project_dir%/public/uploads/headers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true
        product_illustration:
            uri_prefix: /uploads/products
            upload_destination: '%kernel.project_dir%/public/uploads/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true
